/*
  Author: Albert
  Date: 20130417
  Description: Definition of card
*/

#ifndef _CARD_H_
#define _CARD_H_

#include "DataTypes.h"

//
enum CardSuits
{
  SUIT_SPADE = 1, //ºÚÌÒ
  SUIT_HEART,     //ºìÌÒ
  SUIT_DIAMOND,   //Ã·»¨
  SUIT_CLUB       //·½¿é
};

enum CardPoint
{
  POINT_TWO,
  POINT_THREE,
  POINT_FOUR,
  POINT_FIVE,
  POINT_SIX,
  POINT_SEVEN,
  POINT_EIGHT,
  POINT_NINE,
  POINT_TEN,
  POINT_JACK,
  POINT_QUENE,
  POINT_KING,
  POINT_ONE
};

enum CardType
{
  CARD_TYPE_BEGIN,
  TYPE_SLASH, // É±
  TYPE_FIRE_SLASH, // »ðÉ±
  TYPE_THUNDER_SLASH, // À×É±
  TYPE_JINK, // ÉÁ
  TYPE_PEACH, // ÌÒ
  TYPE_WINE, // ¾Æ
  CARD_TYPE_BASIC, // »ù±¾ÅÆ
  TYPE_ARCHERY, // Íò¼ýÆë·¢
  TYPE_ALL_PEACH, // ÌÒÔ°½áÒå
  TYPE_COLLATERAL,  // ½èµ¶É±ÈË
  TYPE_GOOD_HARVEST, // Îå¹È·áµÇ
  TYPE_LIGHTING, // ÉÁµç
  TYPE_FOOD_SHORTAGE, // ±øÁ¸´ç¶Ï
  TYPE_DUEL, // ¾ö¶·
  TYPE_SAVAGE_INVASION, // ÄÏÂùÈëÇÖ
  TYPE_FORGET_HOME, // ÀÖ²»Ë¼Êñ
  TYPE_FIRE_ATTACK, // »ð¹¥
  TYPE_OUT_OF_NOTHING, // ÎÞÖÐÉúÓÐ
  TYPE_STEAL_SHEEP, // Ë³ÊÖÇ£Ñò
  TYPE_BURN_BRIDGE, //  ¹ýºÓ²ðÇÅ
  TYPE_CHAIN, // ÌúË÷Á¬»·
  TYPE_INVULNERABLE, // ÎÞÐ¸¿É»÷
  CARD_TYPE_STRATAGEM, // ½õÄÒÅÆ
  TYPE_CROSSBOW, // Á¬åó
  TYPE_DOUBLE_SWORD, // ´ÆÐÛË«¹É½£
  TYPE_ICE_SWORD, // º®±ù½£
  TYPE_QINGGANG_SWORD, // Çà¸Ö½£
  TYPE_GUDING_SWORD, // ¹Å¶§µ¶
  TYPE_QINGLONG_SWORD, // ÇàÁúÙÈÔÂµ¶
  TYPE_SNAKE_SPEAR, // ÉßÃ¬
  TYPE_INTERSECTING_AXES, // ¹áÊ¯¸«
  TYPE_FANGTIAN_HALBERD, // ·½Ìì»­êª
  TYPE_ROSEFINCH_FAN, // ÖìÈ¸ÓðÉÈ
  TYPE_KYLIN_BOW, // ÷è÷ë¹­
  TYPE_EIGHT_DIAGRAM, // °ËØÔÕó
  TYPE_BENEVOLENT_SHIELD, // ÈÊÍõ¶Ü
  TYPE_SILVER_LION, // °×ÒøÊ¨×Ó
  TYPE_RATTAN_ARMOR, // ÌÙ¼×
  TYPE_RED_HORSE, // ³àÍÃ
  TYPE_DAWAN_HORSE, // ´óÍðÂí
  TYPE_ZIXING_HORSE, // ×ÏóUÂí
  TYPE_DILU_HORSE, // µÄÂ¬
  TYPE_JUEYING_HORSE, // ¾øÓ°
  TYPE_YELLOWTHUNDER_HORSE, // ×¦»Æ·Éµç
  TYPE_HUALIU_HORSE, // æèæò
  CARD_TYPE_EQUIPMENT
};

struct CardInfo
{
  uchar m_CardType;
  uchar m_CardSuit;
  uchar m_CardPoint;
};

const CardInfo BasicCards[] = 
{
  
  {TYPE_SLASH, SUIT_CLUB, POINT_SIX},
  {TYPE_SLASH, SUIT_CLUB, POINT_SEVEN},
  {TYPE_SLASH, SUIT_CLUB, POINT_EIGHT},
  {TYPE_SLASH, SUIT_CLUB, POINT_NINE},
  {TYPE_SLASH, SUIT_CLUB, POINT_TEN},
  {TYPE_SLASH, SUIT_CLUB, POINT_KING},
  {TYPE_SLASH, SUIT_SPADE, POINT_SEVEN},
  {TYPE_SLASH, SUIT_SPADE, POINT_EIGHT},
  {TYPE_SLASH, SUIT_SPADE, POINT_EIGHT},
  {TYPE_SLASH, SUIT_SPADE, POINT_NINE},
  {TYPE_SLASH, SUIT_SPADE, POINT_NINE},
  {TYPE_SLASH, SUIT_SPADE, POINT_TEN},
  {TYPE_SLASH, SUIT_SPADE, POINT_TEN},
  {TYPE_SLASH, SUIT_HEART, POINT_TEN},
  {TYPE_SLASH, SUIT_HEART, POINT_TEN},
  {TYPE_SLASH, SUIT_HEART, POINT_JACK},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_TWO},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_THREE},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_FOUR},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_FIVE},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_SIX},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_SEVEN},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_EIGHT},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_EIGHT},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_NINE},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_NINE},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_TEN},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_TEN},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_JACK},
  {TYPE_SLASH, SUIT_DIAMOND, POINT_JACK},
  {TYPE_JINK, SUIT_CLUB, POINT_TWO},
  {TYPE_JINK, SUIT_CLUB, POINT_TWO},
  {TYPE_JINK, SUIT_CLUB, POINT_THREE},
  {TYPE_JINK, SUIT_CLUB, POINT_FOUR},
  {TYPE_JINK, SUIT_CLUB, POINT_FIVE},
  {TYPE_JINK, SUIT_CLUB, POINT_SIX},
  {TYPE_JINK, SUIT_CLUB, POINT_SEVEN},
  {TYPE_JINK, SUIT_CLUB, POINT_EIGHT},
  {TYPE_JINK, SUIT_CLUB, POINT_NINE},
  {TYPE_JINK, SUIT_CLUB, POINT_TEN},
  {TYPE_JINK, SUIT_CLUB, POINT_JACK},
  {TYPE_JINK, SUIT_CLUB, POINT_JACK},
  {TYPE_JINK, SUIT_HEART, POINT_TWO},
  {TYPE_JINK, SUIT_HEART, POINT_TWO},
  {TYPE_JINK, SUIT_HEART, POINT_KING},
  {TYPE_PEACH, SUIT_CLUB, POINT_QUENE},
  {TYPE_PEACH, SUIT_HEART, POINT_THREE},
  {TYPE_PEACH, SUIT_HEART, POINT_FOUR},
  {TYPE_PEACH, SUIT_HEART, POINT_SIX},
  {TYPE_PEACH, SUIT_HEART, POINT_SEVEN},
  {TYPE_PEACH, SUIT_HEART, POINT_EIGHT},
  {TYPE_PEACH, SUIT_HEART, POINT_NINE},
  {TYPE_PEACH, SUIT_HEART, POINT_QUENE},
  {TYPE_ARCHERY, SUIT_HEART, POINT_ONE},
  {TYPE_ALL_PEACH, SUIT_HEART, POINT_ONE},
  {TYPE_COLLATERAL, SUIT_DIAMOND, POINT_QUENE},
  {TYPE_COLLATERAL, SUIT_DIAMOND, POINT_KING},
  {TYPE_GOOD_HARVEST, SUIT_HEART, POINT_THREE},
  {TYPE_GOOD_HARVEST, SUIT_HEART, POINT_FOUR},
  {TYPE_LIGHTING, SUIT_SPADE, POINT_ONE},
  {TYPE_LIGHTING, SUIT_HEART, POINT_QUENE},
  {TYPE_DUEL, SUIT_CLUB, POINT_ONE},
  {TYPE_DUEL, SUIT_SPADE, POINT_ONE},
  {TYPE_DUEL, SUIT_DIAMOND, POINT_ONE},
  {TYPE_SAVAGE_INVASION, SUIT_SPADE, POINT_SEVEN},
  {TYPE_SAVAGE_INVASION, SUIT_SPADE, POINT_KING},
  {TYPE_SAVAGE_INVASION, SUIT_DIAMOND, POINT_SEVEN},
  {TYPE_FORGET_HOME, SUIT_SPADE, POINT_SIX},
  {TYPE_FORGET_HOME, SUIT_HEART, POINT_SIX},
  {TYPE_FORGET_HOME, SUIT_DIAMOND, POINT_SIX},
  {TYPE_OUT_OF_NOTHING, SUIT_HEART, POINT_SEVEN},
  {TYPE_OUT_OF_NOTHING, SUIT_HEART, POINT_EIGHT},
  {TYPE_OUT_OF_NOTHING, SUIT_HEART, POINT_NINE},
  {TYPE_OUT_OF_NOTHING, SUIT_HEART, POINT_JACK},
  {TYPE_STEAL_SHEEP, SUIT_CLUB, POINT_THREE},
  {TYPE_STEAL_SHEEP, SUIT_CLUB, POINT_FOUR},
  {TYPE_STEAL_SHEEP, SUIT_SPADE, POINT_THREE},
  {TYPE_STEAL_SHEEP, SUIT_SPADE, POINT_FOUR},
  {TYPE_STEAL_SHEEP, SUIT_SPADE, POINT_JACK},
  {TYPE_BURN_BRIDGE, SUIT_SPADE, POINT_THREE},
  {TYPE_BURN_BRIDGE, SUIT_SPADE, POINT_FOUR},
  {TYPE_BURN_BRIDGE, SUIT_SPADE, POINT_QUENE},
  {TYPE_BURN_BRIDGE, SUIT_HEART, POINT_QUENE},
  {TYPE_BURN_BRIDGE, SUIT_DIAMOND, POINT_THREE},
  {TYPE_BURN_BRIDGE, SUIT_DIAMOND, POINT_FOUR},
  {TYPE_INVULNERABLE, SUIT_SPADE, POINT_JACK},
  {TYPE_INVULNERABLE, SUIT_DIAMOND, POINT_QUENE},
  {TYPE_INVULNERABLE, SUIT_DIAMOND, POINT_KING},
  {TYPE_INVULNERABLE, SUIT_CLUB, POINT_QUENE},
  {TYPE_CROSSBOW, SUIT_CLUB, POINT_ONE},
  {TYPE_CROSSBOW, SUIT_DIAMOND, POINT_ONE},
  {TYPE_DOUBLE_SWORD, SUIT_SPADE, POINT_TWO},
  {TYPE_ICE_SWORD, SUIT_SPADE, POINT_TWO},
  {TYPE_QINGGANG_SWORD, SUIT_SPADE, POINT_SIX},
  {TYPE_QINGLONG_SWORD, SUIT_SPADE, POINT_FIVE},
  {TYPE_SNAKE_SPEAR, SUIT_SPADE, POINT_QUENE},
  {TYPE_INTERSECTING_AXES, SUIT_CLUB, POINT_FIVE},
  {TYPE_FANGTIAN_HALBERD, SUIT_CLUB, POINT_QUENE},
  {TYPE_KYLIN_BOW, SUIT_HEART, POINT_FIVE},
  {TYPE_EIGHT_DIAGRAM, SUIT_SPADE, POINT_TWO},
  {TYPE_EIGHT_DIAGRAM, SUIT_DIAMOND, POINT_TWO},
  {TYPE_BENEVOLENT_SHIELD, SUIT_DIAMOND, POINT_TWO},
  {TYPE_RED_HORSE, SUIT_HEART, POINT_FIVE},
  {TYPE_DAWAN_HORSE, SUIT_SPADE, POINT_KING},
  {TYPE_ZIXING_HORSE, SUIT_CLUB, POINT_KING},
  {TYPE_DILU_HORSE, SUIT_DIAMOND, POINT_FIVE},
  {TYPE_JUEYING_HORSE, SUIT_SPADE, POINT_KING},
  {TYPE_YELLOWTHUNDER_HORSE, SUIT_HEART, POINT_FIVE}
};

const CardInfo WarfareCards[] = 
{
  {TYPE_WINE, SUIT_CLUB, POINT_NINE},
  {TYPE_WINE, SUIT_SPADE, POINT_THREE},
  {TYPE_WINE, SUIT_SPADE, POINT_NINE},
  {TYPE_WINE, SUIT_DIAMOND, POINT_THREE},
  {TYPE_WINE, SUIT_DIAMOND, POINT_NINE},
  {TYPE_FIRE_SLASH, SUIT_CLUB, POINT_FOUR},
  {TYPE_FIRE_SLASH, SUIT_CLUB, POINT_FIVE},
  {TYPE_FIRE_SLASH, SUIT_HEART, POINT_FOUR},
  {TYPE_FIRE_SLASH, SUIT_HEART, POINT_SEVEN},
  {TYPE_FIRE_SLASH, SUIT_HEART, POINT_TEN},
  {TYPE_THUNDER_SLASH, SUIT_SPADE, POINT_FOUR},
  {TYPE_THUNDER_SLASH, SUIT_SPADE, POINT_FIVE},
  {TYPE_THUNDER_SLASH, SUIT_SPADE, POINT_SIX},
  {TYPE_THUNDER_SLASH, SUIT_SPADE, POINT_SEVEN},
  {TYPE_THUNDER_SLASH, SUIT_SPADE, POINT_EIGHT},
  {TYPE_THUNDER_SLASH, SUIT_DIAMOND, POINT_FIVE},
  {TYPE_THUNDER_SLASH, SUIT_DIAMOND, POINT_SIX},
  {TYPE_THUNDER_SLASH, SUIT_DIAMOND, POINT_SEVEN},
  {TYPE_THUNDER_SLASH, SUIT_DIAMOND, POINT_EIGHT},
  {TYPE_JINK, SUIT_CLUB, POINT_SIX},
  {TYPE_JINK, SUIT_CLUB, POINT_SEVEN},
  {TYPE_JINK, SUIT_CLUB, POINT_EIGHT},
  {TYPE_JINK, SUIT_CLUB, POINT_TEN},
  {TYPE_JINK, SUIT_CLUB, POINT_JACK},
  {TYPE_JINK, SUIT_HEART, POINT_EIGHT},
  {TYPE_JINK, SUIT_HEART, POINT_NINE},
  {TYPE_JINK, SUIT_HEART, POINT_JACK},
  {TYPE_JINK, SUIT_HEART, POINT_QUENE},
  {TYPE_PEACH, SUIT_CLUB, POINT_TWO},
  {TYPE_PEACH, SUIT_CLUB, POINT_THREE},
  {TYPE_PEACH, SUIT_HEART, POINT_FIVE},
  {TYPE_PEACH, SUIT_HEART, POINT_SIX},
  {TYPE_FOOD_SHORTAGE, SUIT_SPADE, POINT_TEN},
  {TYPE_FOOD_SHORTAGE, SUIT_DIAMOND, POINT_FOUR},
  {TYPE_FIRE_ATTACK, SUIT_CLUB, POINT_QUENE},
  {TYPE_FIRE_ATTACK, SUIT_HEART, POINT_TWO},
  {TYPE_FIRE_ATTACK, SUIT_HEART, POINT_THREE},
  {TYPE_CHAIN, SUIT_SPADE, POINT_JACK},
  {TYPE_CHAIN, SUIT_SPADE, POINT_QUENE},
  {TYPE_CHAIN, SUIT_DIAMOND, POINT_TEN},
  {TYPE_CHAIN, SUIT_DIAMOND, POINT_JACK},
  {TYPE_CHAIN, SUIT_DIAMOND, POINT_QUENE},
  {TYPE_CHAIN, SUIT_DIAMOND, POINT_KING},
  {TYPE_INVULNERABLE, SUIT_SPADE, POINT_KING},
  {TYPE_INVULNERABLE, SUIT_HEART, POINT_ONE},
  {TYPE_INVULNERABLE, SUIT_HEART, POINT_KING},
  {TYPE_GUDING_SWORD, SUIT_SPADE, POINT_ONE},
  {TYPE_ROSEFINCH_FAN, SUIT_CLUB, POINT_ONE},
  {TYPE_SILVER_LION, SUIT_DIAMOND, POINT_ONE},
  {TYPE_RATTAN_ARMOR, SUIT_SPADE, POINT_TWO},
  {TYPE_RATTAN_ARMOR, SUIT_DIAMOND, POINT_TWO},
  {TYPE_HUALIU_HORSE, SUIT_CLUB, POINT_KING}
};


class CCard
{
public:
  CCard();

  uchar GetCardSuit() const { return m_CardInfo.m_CardSuit; }
  void SetCardSuit(uchar cardSuit) { m_CardInfo.m_CardSuit = cardSuit; }
  uchar GetCardPoint() const { return m_CardInfo.m_CardPoint; }
  void SetCardPoint(uchar cardPoint) { m_CardInfo.m_CardPoint = cardPoint; }
  uchar GetCardType() const { return m_CardInfo.m_CardType; }
  void SetCardType(uchar cardType) { m_CardInfo.m_CardType = cardType; }
  ushort GetCardSkillID() const { return m_CardInfo.m_SkillID; }
  void SetCardSkillID(ushort skillID) { m_CardInfo.m_SkillID = skillID; }
  CSkill * GetCardSkill() const { return m_CardSkill; }
  void SetCardSkill(CSkill *skill) { m_CardSkill = skill; }

  int OnUse();

protected:
  CardInfo m_CardInfo;
  CSkill *m_CardSkill;
};

class CCardArray
{
  
};

class CCardPackage
{
};

#endif
